### PR TITLE
update version of packages in README

### PR DESCRIPTION
**Pull request by Clevero**
It seems that the version of the distro packages mentioned here were outdated
The old versions no longer exist and therefor cannot be downloaded

### CODE REVIEW

**Comment by pvital** [comment]
Hello @Clevero 

Unfortunately, Gingerbase project don't accept Pull Requests (that IMO is a bad) to apply contributions to the master branch. 

Please, follow the process described at https://github.com/kimchi-project/gingerbase/wiki/How-to-Contribute and we'll accept your contribution with no problems.

**Comment by Clevero** [comment]
thank your for your response!

I registered my email adress on your mailing list, but it seems that I need to be "activated" by an admin before I can send anything to the mailing list. Is it possible that you can check that? :)

**Comment by pvital** [comment]
@Clevero 

We did not received any subscription request from you. Please, try to subscribe the ML by the following link:

https://groups.google.com/forum/#!forum/ginger-dev-list

**Comment by danielhb** [comment]
HI @Clevero 

The mailing list is hosted @ ginger-dev-list@googlegroups.com. You can ask access at

https://groups.google.com/forum/#!forum/ginger-dev-list/join

I'll accept it as soon as I get the invitation request and then you can send the patch to the ML.

About the pull request, we do not work that way due to how Github handled that in the past. We do not discard using pull requests in the future but at the same time it's not something we are actively discussing in the ML.

**Comment by Clevero** [comment]
Thank you very much for your very friendly responses, even if this is my first patch!

**Pull request closed without merging**
